import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./NextThemeProviders";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ButtonToTop from "@/components/ButtonToTop";
export const metadata: Metadata = {
  title: "Alreda Photograph",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" suppressHydrationWarning>
      <body className="bg-slate-100">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
          <Footer />
          <ButtonToTop />
        </ThemeProvider>
      </body>
    </html>
  );
}
